### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by mbugni** [poperigby/com.github.youda008.DoomRunner#2]
I notice right now this project.
Please take a look at [1] and [2].

[1] https://github.com/mbugni/DoomRunnerFlatpak
[2] https://github.com/Youda008/DoomRunner/issues/105

**Comment by poperigby** [comment]
I couldn't get it to launch engines, so it was pretty much useless without fiddling with scripts. I'm waiting on this https://github.com/flatpak/xdg-desktop-portal/issues/283

**Comment by mbugni** [comment]
Indeed you can run engines outside the sandbox, by using the `flatpak-spawn` command.
Another approach is to package the engine along with the launcher, as I did.
I'm trying to get some help from the author, just to simplify browsing in the sandbox.
Let me know if you are interested in a collaboration: we are working at a duplicate.

**Comment by poperigby** [comment]
Yes, you can use `flatpak-spawn`, but I think I remember running into issues with Flatpaked engines, and wouldn't you need scripts for each of them? I also found the idea of packaging engines with DoomRunner to be unacceptably annoying, so I was just going to wait.

**Comment by mbugni** [comment]
> I remember running into issues with Flatpaked engines, and wouldn't you need scripts for each of them?

I suppose because you are escaping from a jail to jump in another jail.

> I also found the idea of packaging engines with DoomRunner to be unacceptably annoying, so I was just going to wait.

I respect your opinion, but I'm afraid it will be a long wait or even a dream. Flatpak means sandbox, by design. Basically I like it, and such kind of situations (launchers) are border line.

**Comment by poperigby** [comment]
> I respect your opinion, but I'm afraid it will be a long wait or even a dream. Flatpak means sandbox, by design. Basically I like it, and such kind of situations (launchers) are border line.

Yeah, probably :confused:. I'm not very good at Flatpaking apps to begin with, so I doubt I would be much help to you, but I wish you luck packaging it, and I'll certainly use it!

**Comment by mbugni** [comment]
You can collaborate with [Doom Runner on Flathub](https://flathub.org/it/apps/io.github.Youda008.DoomRunner), if you like.

**Comment by poperigby** [comment]
Thanks, I did see that! I'm actually running it myself :slightly_smiling_face:.
